
package org.openiam.idm.srvc.key.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "KeyManagementWS", targetNamespace = "urn:idm.openiam.org/srvc/res/service")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface KeyManagementWS {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "encryptUserData", targetNamespace = "urn:idm.openiam.org/srvc/res/service", className = "org.openiam.idm.srvc.key.service.EncryptUserData")
    @ResponseWrapper(localName = "encryptUserDataResponse", targetNamespace = "urn:idm.openiam.org/srvc/res/service", className = "org.openiam.idm.srvc.key.service.EncryptUserDataResponse")
    String encryptUserData(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
            String arg1);

    /**
     * 
     * @return
     *     returns org.openiam.idm.srvc.key.service.Response
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "initKeyManagement", targetNamespace = "urn:idm.openiam.org/srvc/res/service", className = "org.openiam.idm.srvc.key.service.InitKeyManagement")
    @ResponseWrapper(localName = "initKeyManagementResponse", targetNamespace = "urn:idm.openiam.org/srvc/res/service", className = "org.openiam.idm.srvc.key.service.InitKeyManagementResponse")
    Response initKeyManagement();

    /**
     * 
     * @param secretKey
     * @return
     *     returns org.openiam.idm.srvc.key.service.Response
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "migrateData", targetNamespace = "urn:idm.openiam.org/srvc/res/service", className = "org.openiam.idm.srvc.key.service.MigrateData")
    @ResponseWrapper(localName = "migrateDataResponse", targetNamespace = "urn:idm.openiam.org/srvc/res/service", className = "org.openiam.idm.srvc.key.service.MigrateDataResponse")
    Response migrateData(
            @WebParam(name = "secretKey", targetNamespace = "")
            String secretKey);

    /**
     * 
     * @return
     *     returns byte[]
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "generateCookieKey", targetNamespace = "urn:idm.openiam.org/srvc/res/service", className = "org.openiam.idm.srvc.key.service.GenerateCookieKey")
    @ResponseWrapper(localName = "generateCookieKeyResponse", targetNamespace = "urn:idm.openiam.org/srvc/res/service", className = "org.openiam.idm.srvc.key.service.GenerateCookieKeyResponse")
    byte[] generateCookieKey()
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns byte[]
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCookieKey", targetNamespace = "urn:idm.openiam.org/srvc/res/service", className = "org.openiam.idm.srvc.key.service.GetCookieKey")
    @ResponseWrapper(localName = "getCookieKeyResponse", targetNamespace = "urn:idm.openiam.org/srvc/res/service", className = "org.openiam.idm.srvc.key.service.GetCookieKeyResponse")
    byte[] getCookieKey()
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns org.openiam.idm.srvc.key.service.Response
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "generateMasterKey", targetNamespace = "urn:idm.openiam.org/srvc/res/service", className = "org.openiam.idm.srvc.key.service.GenerateMasterKey")
    @ResponseWrapper(localName = "generateMasterKeyResponse", targetNamespace = "urn:idm.openiam.org/srvc/res/service", className = "org.openiam.idm.srvc.key.service.GenerateMasterKeyResponse")
    Response generateMasterKey();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "decryptUserData", targetNamespace = "urn:idm.openiam.org/srvc/res/service", className = "org.openiam.idm.srvc.key.service.DecryptUserData")
    @ResponseWrapper(localName = "decryptUserDataResponse", targetNamespace = "urn:idm.openiam.org/srvc/res/service", className = "org.openiam.idm.srvc.key.service.DecryptUserDataResponse")
    String decryptUserData(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
            String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "decryptData", targetNamespace = "urn:idm.openiam.org/srvc/res/service", className = "org.openiam.idm.srvc.key.service.DecryptData")
    @ResponseWrapper(localName = "decryptDataResponse", targetNamespace = "urn:idm.openiam.org/srvc/res/service", className = "org.openiam.idm.srvc.key.service.DecryptDataResponse")
    String decryptData(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "encryptData", targetNamespace = "urn:idm.openiam.org/srvc/res/service", className = "org.openiam.idm.srvc.key.service.EncryptData")
    @ResponseWrapper(localName = "encryptDataResponse", targetNamespace = "urn:idm.openiam.org/srvc/res/service", className = "org.openiam.idm.srvc.key.service.EncryptDataResponse")
    String encryptData(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0);

}
