use openiam;

UPDATE USERS SET COMPANY_ID=null WHERE COMPANY_ID='';

ALTER TABLE USERS
  ADD CONSTRAINT FK_USERS_COMPANY FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (COMPANY_ID),
  ADD INDEX FK_USERS_COMPANY (COMPANY_ID ASC);
