use openiam;

DELETE FROM GRP_ROLE WHERE ROLE_ID IN(SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME IS NULL);
DELETE FROM PERMISSIONS WHERE ROLE_ID IN(SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME IS NULL);
DELETE FROM RESOURCE_POLICY WHERE ROLE_ID IN(SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME IS NULL);
DELETE FROM RESOURCE_ROLE WHERE ROLE_ID IN(SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME IS NULL);
DELETE FROM ROLE_ATTRIBUTE WHERE ROLE_ID IN(SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME IS NULL);
DELETE FROM ROLE_POLICY WHERE ROLE_ID IN(SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME IS NULL);
DELETE FROM USER_ROLE WHERE ROLE_ID IN(SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME IS NULL);
DELETE FROM role_to_role_membership WHERE ROLE_ID IN(SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME IS NULL);
DELETE FROM role_to_role_membership WHERE MEMBER_ROLE_ID IN(SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME IS NULL);
ALTER TABLE ROLE MODIFY COLUMN ROLE_NAME VARCHAR(80) NOT NULL;