use openiam;

START TRANSACTION;

/*DROP all references to the Role Table*/

ALTER TABLE GRP_ROLE DROP FOREIGN KEY FK_GRP_ROLE_ROLE;

ALTER TABLE GRP_ROLE DROP INDEX FK_GRP_ROLE_ROLE;

ALTER TABLE GRP_ROLE DROP PRIMARY KEY;

ALTER TABLE RESOURCE_ROLE DROP FOREIGN KEY FK_RESOURCE_ROLE_ROLE;

ALTER TABLE RESOURCE_ROLE DROP INDEX FK_RESOURCE_ROLE_ROLE;

ALTER TABLE RESOURCE_ROLE DROP FOREIGN KEY FK_RESOURCE_ROLE_RESOURCE;

ALTER TABLE RESOURCE_ROLE DROP PRIMARY KEY;

ALTER TABLE RESOURCE_ROLE ADD CONSTRAINT FK_RESOURCE_ROLE_RESOURCE FOREIGN KEY (RESOURCE_ID) REFERENCES RES(RESOURCE_ID);

ALTER TABLE ROLE_ATTRIBUTE DROP FOREIGN KEY FK_ROLE_ROLE_ATTRIBUTE;

ALTER TABLE ROLE_ATTRIBUTE DROP INDEX FK_ROLE_ROLE_ATTRIBUTE;

ALTER TABLE USER_ROLE DROP FOREIGN KEY FK_USR_ROLE_ROLE;

ALTER TABLE USER_ROLE DROP INDEX FK_USR_ROLE_ROLE;

ALTER TABLE USER_ROLE DROP PRIMARY KEY;

ALTER TABLE ROLE_POLICY DROP FOREIGN KEY ROLE_POLICY_ibfk_1; # this might break

ALTER TABLE ROLE_POLICY DROP INDEX ROLE_ID;

DROP TABLE ROLE_ENTITLEMENT;

DROP VIEW USER_ROLE_VW;

ALTER TABLE RESOURCE_POLICY DROP FOREIGN KEY RS_PL_RL_RLID;

ALTER TABLE RESOURCE_POLICY DROP KEY RS_PL_RL_RLID;

ALTER TABLE PERMISSIONS DROP PRIMARY KEY;

ALTER TABLE ROLE DROP FOREIGN KEY FK_ROLE_SERVICE;

ALTER TABLE ROLE DROP INDEX FK_ROLE_SERVICE;

ALTER TABLE ROLE DROP PRIMARY KEY;

ALTER TABLE ROLE ADD CONSTRAINT FK_ROLE_SERVICE FOREIGN KEY (SERVICE_ID) REFERENCES SECURITY_DOMAIN(DOMAIN_ID);

/*Add the new ID, and populate it via stored procedure (no better way to do this)*/
ALTER TABLE ROLE ADD TEMP_ROLE_ID varchar(32) NULL;

DELIMITER $$

DROP PROCEDURE IF EXISTS generateSimpleRoleId$$

CREATE PROCEDURE generateSimpleRoleId()
	BEGIN
		DECLARE done INT DEFAULT FALSE;
		DECLARE role, service, roleId VARCHAR(32);		
		DECLARE newId INT DEFAULT 1;
		DECLARE cur1 CURSOR FOR (SELECT ROLE_ID, SERVICE_ID, TEMP_ROLE_ID FROM ROLE);
		DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = TRUE;
		OPEN cur1;
		
		REPEAT 
			FETCH cur1 INTO role, service, roleId;
			IF (roleId IS NULL) THEN
				UPDATE ROLE SET TEMP_ROLE_ID=newId WHERE SERVICE_ID=service AND ROLE_ID=role;
				SET newId = newId + 1;
			END IF;
		UNTIL done END REPEAT; 
				
		
		CLOSE cur1;
	END$$
DELIMITER ;

call generateSimpleRoleId();

DROP PROCEDURE generateSimpleRoleId;

/*create the reference column on all tables referencing ROLE, and populate it*/
ALTER TABLE GRP_ROLE ADD TEMP_ROLE_ID varchar(32) NULL;

UPDATE GRP_ROLE r SET TEMP_ROLE_ID= (
	SELECT TEMP_ROLE_ID FROM ROLE WHERE ROLE_ID=r.ROLE_ID AND SERVICE_ID=r.SERVICE_ID
);

ALTER TABLE RESOURCE_ROLE ADD TEMP_ROLE_ID varchar(32) NULL;

UPDATE RESOURCE_ROLE r SET TEMP_ROLE_ID= (
	SELECT TEMP_ROLE_ID FROM ROLE WHERE ROLE_ID=r.ROLE_ID AND SERVICE_ID=r.SERVICE_ID
);

ALTER TABLE ROLE_ATTRIBUTE ADD TEMP_ROLE_ID varchar(32) NULL;

UPDATE ROLE_ATTRIBUTE r SET TEMP_ROLE_ID= (
	SELECT TEMP_ROLE_ID FROM ROLE WHERE ROLE_ID=r.ROLE_ID AND SERVICE_ID=r.SERVICE_ID
);

ALTER TABLE USER_ROLE ADD TEMP_ROLE_ID varchar(32) NULL;

UPDATE USER_ROLE r SET TEMP_ROLE_ID= (
	SELECT TEMP_ROLE_ID FROM ROLE WHERE ROLE_ID=r.ROLE_ID AND SERVICE_ID=r.SERVICE_ID
);

ALTER TABLE ROLE_POLICY ADD TEMP_ROLE_ID varchar(32) NULL;

UPDATE ROLE_POLICY r SET TEMP_ROLE_ID= (
	SELECT TEMP_ROLE_ID FROM ROLE WHERE ROLE_ID=r.ROLE_ID AND SERVICE_ID=r.SERVICE_ID
);

ALTER TABLE RESOURCE_POLICY ADD TEMP_ROLE_ID varchar(32) NULL;

UPDATE RESOURCE_POLICY r SET TEMP_ROLE_ID= (
	SELECT TEMP_ROLE_ID FROM ROLE WHERE ROLE_ID=r.ROLE_ID AND SERVICE_ID=r.SERVICE_ID
);

ALTER TABLE PERMISSIONS ADD COLUMN TEMP_ROLE_ID varchar(32);

UPDATE PERMISSIONS r SET TEMP_ROLE_ID=(
	SELECT TEMP_ROLE_ID FROM ROLE WHERE ROLE_ID=r.ROLE_ID AND SERVICE_ID=r.SERVICE_ID
);

/*drop the old column that referenced the composite key*/
ALTER TABLE GRP_ROLE DROP COLUMN SERVICE_ID;

ALTER TABLE GRP_ROLE DROP COLUMN ROLE_ID;

ALTER TABLE RESOURCE_ROLE DROP COLUMN SERVICE_ID;

ALTER TABLE RESOURCE_ROLE DROP COLUMN ROLE_ID;

ALTER TABLE ROLE_ATTRIBUTE DROP COLUMN SERVICE_ID;

ALTER TABLE ROLE_ATTRIBUTE DROP COLUMN ROLE_ID;

ALTER TABLE USER_ROLE DROP COLUMN SERVICE_ID;

ALTER TABLE USER_ROLE DROP COLUMN ROLE_ID;

ALTER TABLE ROLE_POLICY DROP COLUMN SERVICE_ID;

ALTER TABLE ROLE_POLICY DROP COLUMN ROLE_ID;

ALTER TABLE RESOURCE_POLICY DROP COLUMN SERVICE_ID;

ALTER TABLE RESOURCE_POLICY DROP COLUMN ROLE_ID;

ALTER TABLE PERMISSIONS DROP COLUMN SERVICE_ID;

ALTER TABLE PERMISSIONS DROP COLUMN ROLE_ID;

ALTER TABLE ROLE DROP COLUMN ROLE_ID;

/*rename the TEMP_ROLE_ID columns to be ROLE_ID NOT NULL*/
alter table GRP_ROLE CHANGE TEMP_ROLE_ID ROLE_ID varchar(32) NOT NULL;

alter table RESOURCE_ROLE CHANGE TEMP_ROLE_ID ROLE_ID varchar(32) NOT NULL;

alter table ROLE_ATTRIBUTE CHANGE TEMP_ROLE_ID ROLE_ID varchar(32) NOT NULL;

alter table USER_ROLE CHANGE TEMP_ROLE_ID ROLE_ID varchar(32) NOT NULL;

alter table ROLE_POLICY CHANGE TEMP_ROLE_ID ROLE_ID varchar(32) NOT NULL;

alter table RESOURCE_POLICY CHANGE TEMP_ROLE_ID ROLE_ID varchar(32) NOT NULL;

alter table ROLE CHANGE TEMP_ROLE_ID ROLE_ID varchar(32) NOT NULL;

/* it is possible that PERMISSIONS records did not map to an existing Role or Menu - delete those */
DELETE FROM PERMISSIONS WHERE TEMP_ROLE_ID IS NULL OR TEMP_ROLE_ID='';
DELETE FROM PERMISSIONS WHERE MENU_ID NOT IN (
	SELECT MENU_ID FROM MENU
);

alter table PERMISSIONS CHANGE TEMP_ROLE_ID ROLE_ID varchar(32) NOT NULL;

/*make ROLE_ID primary on ROLE*/
ALTER TABLE ROLE ADD PRIMARY KEY (ROLE_ID);

/*add foreign keys to the new column*/
ALTER TABLE GRP_ROLE ADD CONSTRAINT FK_GRP_ROLE_ROLE FOREIGN KEY(ROLE_ID) REFERENCES ROLE(ROLE_ID);

ALTER TABLE RESOURCE_ROLE ADD CONSTRAINT FK_RESOURCE_ROLE_ROLE FOREIGN KEY(ROLE_ID) REFERENCES ROLE(ROLE_ID);

ALTER TABLE ROLE_ATTRIBUTE ADD CONSTRAINT FK_ROLE_ROLE_ATTRIBUTE FOREIGN KEY(ROLE_ID) REFERENCES ROLE(ROLE_ID);

ALTER TABLE USER_ROLE ADD CONSTRAINT FK_USR_ROLE_ROLE FOREIGN KEY(ROLE_ID) REFERENCES ROLE(ROLE_ID);

ALTER TABLE ROLE_POLICY ADD CONSTRAINT FK_ROLE_POLICY_ROLE FOREIGN KEY(ROLE_ID) REFERENCES ROLE(ROLE_ID);

ALTER TABLE RESOURCE_POLICY ADD CONSTRAINT FK_RESOURCE_POLICY_ROLE FOREIGN KEY(ROLE_ID) REFERENCES ROLE(ROLE_ID);

ALTER TABLE PERMISSIONS ADD CONSTRAINT FK_PERMISSIONS_ROLE FOREIGN KEY(ROLE_ID) REFERENCES ROLE(ROLE_ID);

ALTER TABLE PERMISSIONS ADD CONSTRAINT FK_PERMISSIONS_MENU FOREIGN KEY(MENU_ID) REFERENCES MENU(MENU_ID);

/*recreate primary keys*/
ALTER TABLE GRP_ROLE ADD PRIMARY KEY (GRP_ID, ROLE_ID);

ALTER TABLE RESOURCE_ROLE ADD PRIMARY KEY (RESOURCE_ID, ROLE_ID, PRIVILEGE_ID);

ALTER TABLE USER_ROLE add PRIMARY KEY (ROLE_ID, USER_ID);

ALTER TABLE PERMISSIONS ADD PRIMARY KEY (MENU_ID, ROLE_ID);

/*make the ROLE names unique, if not already*/
DELIMITER $$

DROP PROCEDURE IF EXISTS makeRoleNamesUnique$$

CREATE PROCEDURE makeRoleNamesUnique()
	BEGIN
		DECLARE done INT DEFAULT FALSE;
		DECLARE id VARCHAR(32);
		DECLARE name VARCHAR(80);
		DECLARE service VARCHAR(20);
		DECLARE newId INT DEFAULT 1;
		DECLARE cur1 CURSOR FOR (SELECT ROLE_ID, SERVICE_ID, ROLE_NAME FROM ROLE);
		DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = TRUE;
		OPEN cur1;
		
		REPEAT 
			FETCH cur1 INTO id, service, name;
			IF ((SELECT count(*) FROM ROLE WHERE ROLE_NAME=name) > 1) THEN
				UPDATE ROLE SET ROLE_NAME= CONCAT(name, '_',service) WHERE ROLE_ID=id;
			END IF;
		UNTIL done END REPEAT; 
				
		
		CLOSE cur1;
	END$$
DELIMITER ;

call makeRoleNamesUnique();

DROP PROCEDURE makeRoleNamesUnique;

/*add the unique constraint*/
ALTER TABLE ROLE ADD UNIQUE(ROLE_NAME);

COMMIT;