use openiam;

ALTER TABLE resource_role DROP FOREIGN KEY FK_RESOURCE_ROLE_RESOURCE;
ALTER TABLE resource_role DROP FOREIGN KEY FK_RESOURCE_ROLE_ROLE;
ALTER TABLE resource_role DROP INDEX FK_RESOURCE_ROLE_ROLE;
ALTER TABLE resource_role DROP PRIMARY KEY;
ALTER TABLE resource_role DROP COLUMN PRIVILEGE_ID;
ALTER TABLE resource_role DROP COLUMN PERMIT;
ALTER TABLE resource_role ADD CONSTRAINT FK_RESOURCE_ROLE_RESOURCE FOREIGN KEY (RESOURCE_ID) REFERENCES RES(RESOURCE_ID);
ALTER TABLE resource_role ADD CONSTRAINT FK_RESOURCE_ROLE_ROLE FOREIGN KEY(role_id) REFERENCES role(role_id);
ALTER TABLE resource_role ADD PRIMARY KEY (RESOURCE_ID, ROLE_ID);