package org.openiam.idm.srvc.recon.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

import org.openiam.base.KeyDTO;
import org.openiam.dozer.DozerDTOCorrespondence;
import org.openiam.idm.srvc.recon.domain.ReconciliationSituationEntity;

// Generated May 29, 2010 8:20:09 PM by Hibernate Tools 3.2.2.GA

/**
 * ReconiliationSituation generated by hbm2java
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReconciliationSituation", propOrder = {
        "reconConfigId", "situation", "situationResp", "script", "customCommandScript" })
@DozerDTOCorrespondence(ReconciliationSituationEntity.class)
public class ReconciliationSituation extends KeyDTO {

    private static final long serialVersionUID = -8870989951105414407L;
    private String reconConfigId;
    private String situation;
    private String situationResp;
    private String script;
    private String customCommandScript;

    public ReconciliationSituation() {
    }
    
    public ReconciliationSituation(String id, String situation) {
        setId(id);
        this.situation = situation;
    }

    public String getCustomCommandScript() {
        return customCommandScript;
    }

    public void setCustomCommandScript(String customCommandScript) {
        this.customCommandScript = customCommandScript;
    }

    public String getReconConfigId() {
        return this.reconConfigId;
    }

    public void setReconConfigId(String reconConfigId) {
        this.reconConfigId = reconConfigId;
    }

    public String getSituation() {
        return this.situation;
    }

    public void setSituation(String situation) {
        this.situation = situation;
    }

    public String getSituationResp() {
        return this.situationResp;
    }

    public void setSituationResp(String situationResp) {
        this.situationResp = situationResp;
    }

    public String getScript() {
        return script;
    }

    public void setScript(String script) {
        this.script = script;
    }

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = super.hashCode();
		result = prime
				* result
				+ ((customCommandScript == null) ? 0 : customCommandScript
						.hashCode());
		result = prime * result
				+ ((reconConfigId == null) ? 0 : reconConfigId.hashCode());
		result = prime * result + ((script == null) ? 0 : script.hashCode());
		result = prime * result
				+ ((situation == null) ? 0 : situation.hashCode());
		result = prime * result
				+ ((situationResp == null) ? 0 : situationResp.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (!super.equals(obj))
			return false;
		if (getClass() != obj.getClass())
			return false;
		ReconciliationSituation other = (ReconciliationSituation) obj;
		if (customCommandScript == null) {
			if (other.customCommandScript != null)
				return false;
		} else if (!customCommandScript.equals(other.customCommandScript))
			return false;
		if (reconConfigId == null) {
			if (other.reconConfigId != null)
				return false;
		} else if (!reconConfigId.equals(other.reconConfigId))
			return false;
		if (script == null) {
			if (other.script != null)
				return false;
		} else if (!script.equals(other.script))
			return false;
		if (situation == null) {
			if (other.situation != null)
				return false;
		} else if (!situation.equals(other.situation))
			return false;
		if (situationResp == null) {
			if (other.situationResp != null)
				return false;
		} else if (!situationResp.equals(other.situationResp))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "ReconciliationSituation [reconConfigId=" + reconConfigId
				+ ", situation=" + situation + ", situationResp="
				+ situationResp + ", script=" + script
				+ ", customCommandScript=" + customCommandScript + ", id=" + id
				+ ", objectState=" + objectState + ", requestorSessionID="
				+ requestorSessionID + ", requestorUserId=" + requestorUserId
				+ ", requestorLogin=" + requestorLogin + ", requestClientIP="
				+ requestClientIP + "]";
	}
    
    
}
