use openiam;

DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID IN(
	'AM_PROV_AM_ATTR'
);

DELETE FROM RESOURCE_PROP WHERE RESOURCE_ID IN(
	'AM_PROV_AM_ATTR'
);

DELETE FROM RES WHERE RESOURCE_ID IN(
	'AM_PROV_AM_ATTR'
);

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, DESCRIPTION, URL) VALUES('AM_PROV_AM_ATTR', 'MENU_ITEM', 'AM_PROV_AM_ATTR', 'Create Authentication Provider', '/webconsole-am/authProviderAMAttributes.html');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('AM_PROV_AM_ATTR_PUB', 'AM_PROV_AM_ATTR', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('AM_PROV_AM_ATTR_DESC', 'AM_PROV_AM_ATTR', 'MENU_DISPLAY_NAME', 'Request Attributes');

INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('AM_PROV_EDIT', 'AM_PROV_AM_ATTR');