use openiam;

INSERT INTO METADATA_TYPE (TYPE_ID, DESCRIPTION, ACTIVE, SYNC_MANAGED_SYS) VALUES('MENU_ITEM', 'Menu Item Type', 1, 1);
INSERT INTO METADATA_TYPE (TYPE_ID, DESCRIPTION, ACTIVE, SYNC_MANAGED_SYS) VALUES('AUTHENTICATION_PROVIDER', 'Authentication Provider', 1, 1);
INSERT INTO RESOURCE_TYPE (RESOURCE_TYPE_ID, DESCRIPTION, METADATA_TYPE_ID) VALUES ('AUTH_PROVIDER', 'Authentication Provider', 'AUTHENTICATION_PROVIDER');