use openiam;

UPDATE RES SET IS_PUBLIC='Y' WHERE NAME='SELFSERVICE';

DELETE FROM RESOURCE_PROP WHERE RESOURCE_ID IN('SELFSERVICE_MYINFO', 'SELFSERVICE_MYAPPS');
DELETE FROM res_to_res_membership WHERE RESOURCE_ID IN('SELFSERVICE_MYINFO', 'SELFSERVICE_MYAPPS');
DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID IN('SELFSERVICE_MYINFO', 'SELFSERVICE_MYAPPS');
DELETE FROM RES WHERE RESOURCE_ID IN('SELFSERVICE_MYINFO', 'SELFSERVICE_MYAPPS');


INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, DESCRIPTION, URL) VALUES('SELFSERVICE_MYINFO', 'MENU_ITEM', 'SELFSERVICE_MYINFO', 'My Info', '/selfservice/myInfo.html');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('SELFSERVICE_MYINFO_PUB', 'SELFSERVICE_MYINFO', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('SELFSERVICE_MYINFO_DESC', 'SELFSERVICE_MYINFO', 'MENU_DISPLAY_NAME', 'My Info');
INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('SELFSERVICE', 'SELFSERVICE_MYINFO');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, DESCRIPTION, URL) VALUES('SELFSERVICE_MYAPPS', 'MENU_ITEM', 'SELFSERVICE_MYAPPS', 'My Applications', '/selfservice/myApplications.html');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('SELFSERVICE_MYAPPS_PUB', 'SELFSERVICE_MYAPPS', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('SELFSERVICE_MYAPPS_DESC', 'SELFSERVICE_MYAPPS', 'MENU_DISPLAY_NAME', 'My Applications');
INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('SELFSERVICE', 'SELFSERVICE_MYAPPS');