use openiam;

UPDATE RES SET URL='/webconsole-idm/provisioning/connectorlist.html' where RESOURCE_ID='PROVCONNECT';

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, DESCRIPTION, URL) VALUES('PROVCONNECT_MENU_ITEM', 'MENU_ITEM', 'PROVCONNECT_MENU_ITEM', 'Provisioning Connectors', '/webconsole-idm/provisioning/connectorlist.html');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('PROVCONNECT_PUB', 'PROVCONNECT_MENU_ITEM', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('PROVCONNECT_DESC', 'PROVCONNECT_MENU_ITEM', 'MENU_DISPLAY_NAME', 'Provisioning Connectors');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, DESCRIPTION, URL) VALUES('PROV_CONNECTOR_NEW', 'MENU_ITEM', 'PROV_CONNECTOR_NEW', 'Create Provisioning Connector', '/webconsole-idm/provisioning/connector.html');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('PROV_CONNECTOR_NEW_PUB', 'PROV_CONNECTOR_NEW', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('PROV_CONNECTOR_DSC', 'PROV_CONNECTOR_NEW', 'MENU_DISPLAY_NAME', 'Create New Connector');

INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('PROVCONNECT_MENU_ITEM', 'PROV_CONNECTOR_NEW');
