use openiam;

UPDATE RES SET URL='/webconsole/policyMap.html' WHERE RESOURCE_ID='RESPOLICYMAP';

UPDATE RES SET URL='/webconsole/reconConfig.html' WHERE RESOURCE_ID='RESRECONCILE';

DELETE FROM res_to_res_membership WHERE RESOURCE_ID='RESOURCE_MENU_ROOT' AND MEMBER_RESOURCE_ID='RESPOLICYMAP';
DELETE FROM res_to_res_membership WHERE RESOURCE_ID='RESOURCE_EDIT_PAGE_ROOT' AND MEMBER_RESOURCE_ID='RESPOLICYMAP';

INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('RESOURCE_EDIT_PAGE_ROOT', 'RESPOLICYMAP');

