USE openiam;

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, DISPLAY_ORDER, IS_PUBLIC, IS_SSL) VALUES ('MNGSYS_EDIT_MENU_ROOT', 'MENU_ITEM', NULL, 'MNGSYS_EDIT_MENU_ROOT', 1, 'Y', 'N');

UPDATE RES SET URL='/webconsole/reconciliationEdit.html' WHERE RESOURCE_ID='RESRECONCILE';
UPDATE res_to_res_membership SET RESOURCE_ID='MNGSYS_EDIT_MENU_ROOT' WHERE MEMBER_RESOURCE_ID='RESRECONCILE';
UPDATE res_to_res_membership SET RESOURCE_ID='MNGSYS_EDIT_MENU_ROOT' WHERE MEMBER_RESOURCE_ID='RESPOLICYMAP';

INSERT INTO RES (RESOURCE_ID, NAME, RESOURCE_TYPE_ID, DESCRIPTION, DISPLAY_ORDER, URL, IS_PUBLIC, IS_SSL) VALUES ('MNGSYS_EDIT','MNGSYS_EDIT', 'MENU_ITEM', 'Edit managed system', 1, '/webconsole-idm/provisioning/mngsystem.html', 'Y', 'N');

INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES ('MNGSYS_EDIT_MENU_ROOT', 'MNGSYS_EDIT');

INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('MNGSYS_EDIT_DESC', 'MNGSYS_EDIT', 'MENU_DISPLAY_NAME', 'Edit managed system');

