use openiam;

INSERT INTO METADATA_TYPE(TYPE_ID, DESCRIPTION, SYNC_MANAGED_SYS) VALUES('AD_GROUP_TYPE','AD GROUP TYPE', 0);
INSERT INTO METADATA_TYPE(TYPE_ID, DESCRIPTION, SYNC_MANAGED_SYS) VALUES('LDAP_GROUP_TYPE','LDAP GROUP TYPE', 0);
INSERT INTO METADATA_TYPE(TYPE_ID, DESCRIPTION, SYNC_MANAGED_SYS) VALUES('DEFAULT_GROUP','DEFAULT GROUP TYPE', 0);

INSERT INTO CATEGORY (category_id, parent_id, category_name, show_list) VALUES('GROUP_TYPE', 'ROOT', 'Group Type',0);

INSERT INTO CATEGORY_TYPE (category_id, type_id) VALUES('GROUP_TYPE','AD_GROUP_TYPE');
INSERT INTO CATEGORY_TYPE (category_id, type_id) VALUES('GROUP_TYPE','LDAP_GROUP_TYPE');
INSERT INTO CATEGORY_TYPE (category_id, type_id) VALUES('GROUP_TYPE','DEFAULT_GROUP');