use openiam;

ALTER TABLE GRP DROP COLUMN POLICY_ID;
ALTER TABLE GRP DROP COLUMN GROUP_APPROVER_ID;
ALTER TABLE GRP DROP COLUMN PARENT_GRP_ID;
ALTER TABLE GRP DROP COLUMN INHERIT_FROM_PARENT;
ALTER TABLE GRP DROP COLUMN GROUP_CLASS;