use openiam;

ALTER TABLE RESOURCE_ROLE DROP FOREIGN KEY FK_RESOURCE_ROLE_RESOURCE;
ALTER TABLE RESOURCE_ROLE DROP FOREIGN KEY FK_RESOURCE_ROLE_ROLE;
ALTER TABLE RESOURCE_ROLE DROP INDEX FK_RESOURCE_ROLE_ROLE;
ALTER TABLE RESOURCE_ROLE DROP PRIMARY KEY;
ALTER TABLE RESOURCE_ROLE DROP COLUMN PRIVILEGE_ID;
ALTER TABLE RESOURCE_ROLE DROP COLUMN PERMIT;
ALTER TABLE RESOURCE_ROLE ADD CONSTRAINT FK_RESOURCE_ROLE_RESOURCE FOREIGN KEY (RESOURCE_ID) REFERENCES RES(RESOURCE_ID);
ALTER TABLE RESOURCE_ROLE ADD CONSTRAINT FK_RESOURCE_ROLE_ROLE FOREIGN KEY(ROLE_ID) REFERENCES ROLE(ROLE_ID);
ALTER TABLE RESOURCE_ROLE ADD PRIMARY KEY (RESOURCE_ID, ROLE_ID);