use openiam;

UPDATE RES SET URL='/webconsole-idm/provisioning/mngsystemlist.html' where RESOURCE_ID='MNGSYS';

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, DESCRIPTION, URL) VALUES('MNGSYS_MENU_ITEM', 'MENU_ITEM', 'MNGSYS_MENU_ITEM', 'Managed Systems', '/webconsole-idm/provisioning/mngsystemlist.html');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('MNGSYS_PUB', 'MNGSYS_MENU_ITEM', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('MNGSYS_DESC', 'MNGSYS_MENU_ITEM', 'MENU_DISPLAY_NAME', 'Managed Systems');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, DESCRIPTION, URL) VALUES('MNGSYS_NEW', 'MENU_ITEM', 'MNGSYS_NEW', 'Create Managed System', '/webconsole-idm/provisioning/mngsystem.html');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('MNGSYS_NEW_PUB', 'MNGSYS_NEW', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('MNGSYS_DSC', 'MNGSYS_NEW', 'MENU_DISPLAY_NAME', 'Create New Managed System');


INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('MNGSYS', 'MNGSYS_NEW');

