use openiam;

INSERT INTO METADATA_TYPE (TYPE_ID, DESCRIPTION, ACTIVE, SYNC_MANAGED_SYS) VALUES('UI_WIDGET', 'UI_WIDGET', 'Y', 'Y');
INSERT INTO METADATA_TYPE (TYPE_ID, DESCRIPTION, ACTIVE, SYNC_MANAGED_SYS) VALUES('UI_TEMPLATE', 'UI_TEMPLATE', 'Y', 'Y');
INSERT INTO RESOURCE_TYPE (RESOURCE_TYPE_ID, DESCRIPTION, METADATA_TYPE_ID) VALUES('UI_WIDGET', 'UI Widget', 'UI_WIDGET');
INSERT INTO RESOURCE_TYPE (RESOURCE_TYPE_ID, DESCRIPTION, METADATA_TYPE_ID) VALUES('UI_TEMPLATE', 'UI Template', 'UI_TEMPLATE');