USE openiam;
UPDATE RES SET URL='/webconsole/policyMap.html' WHERE RESOURCE_ID='RESPOLICYMAP';
UPDATE RES SET URL='/webconsole/reconConfig.html' WHERE RESOURCE_ID='RESRECONCILE';
UPDATE res_to_res_membership SET RESOURCE_ID='RESOURCE_EDIT_PAGE_ROOT' WHERE RESOURCE_ID='RESOURCE_MENU_ROOT' and MEMBER_RESOURCE_ID='RESPOLICYMAP';


