
package org.openiam.idm.srvc.key.service;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "KeyManagementWS", targetNamespace = "urn:idm.openiam.org/srvc/key/service", wsdlLocation = "http://localhost:9080/openiam-esb/idmsrvc/KeyManagementWS?wsdl")
public class KeyManagementWS_Service
    extends Service
{
    public final static URL WSDL_LOCATION;
    public final static QName SERVICE_NAME = new QName("urn:idm.openiam.org/srvc/key/service", "KeyManagementWS");
    private final static WebServiceException KEYMANAGEMENTWS_EXCEPTION;

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9080/openiam-esb/idmsrvc/KeyManagementWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSDL_LOCATION = url;
        KEYMANAGEMENTWS_EXCEPTION = e;
    }

    public KeyManagementWS_Service() {
        super(__getWsdlLocation(), SERVICE_NAME);
    }

    public KeyManagementWS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICE_NAME, features);
    }

    public KeyManagementWS_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE_NAME);
    }

    public KeyManagementWS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICE_NAME, features);
    }

    public KeyManagementWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public KeyManagementWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns KeyManagementWS
     */
    @WebEndpoint(name = "KeyManagementWSPort")
    public KeyManagementWS getKeyManagementWSPort() {
        return super.getPort(new QName("urn:idm.openiam.org/srvc/key/service", "KeyManagementWSPort"), KeyManagementWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns KeyManagementWS
     */
    @WebEndpoint(name = "KeyManagementWSPort")
    public KeyManagementWS getKeyManagementWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:idm.openiam.org/srvc/key/service", "KeyManagementWSPort"), KeyManagementWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (KEYMANAGEMENTWS_EXCEPTION!= null) {
            throw KEYMANAGEMENTWS_EXCEPTION;
        }
        return WSDL_LOCATION;
    }

}
