use openiam;

INSERT INTO METADATA_TYPE (TYPE_ID, DESCRIPTION, ACTIVE, SYNC_MANAGED_SYS) VALUES('CONTENT_PROVIDER', 'Content Provider', 1, 1);
INSERT INTO METADATA_TYPE (TYPE_ID, DESCRIPTION, ACTIVE, SYNC_MANAGED_SYS) VALUES('URL_PATTERN', 'Url Pattern', 1, 1);
INSERT INTO RESOURCE_TYPE (RESOURCE_TYPE_ID, DESCRIPTION, METADATA_TYPE_ID) VALUES ('CONTENT_PROVIDER', 'Content Provider', 'CONTENT_PROVIDER');
INSERT INTO RESOURCE_TYPE (RESOURCE_TYPE_ID, DESCRIPTION, METADATA_TYPE_ID) VALUES ('URL_PATTERN', 'Url Pattern', 'URL_PATTERN');