UPDATE RES SET URL='/webconsole/resources.html' WHERE RESOURCE_ID='SECURITY_RES';

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, DESCRIPTION) VALUES('RESOURCE_MENU_ROOT', 'MENU_ITEM', 'RESOURCE_MENU_ROOT', 'Root for Resource Context Menu');

UPDATE RES_TO_RES_MEMBERSHIP SET RESOURCE_ID='RESOURCE_MENU_ROOT' WHERE RESOURCE_ID='SECURITY_RES';

UPDATE RES SET URL='/webconsole/resources.html' WHERE RESOURCE_ID='RESSUMMARY';

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, DESCRIPTION, URL) VALUES('CREATE_RESOURCE_MENU', 'MENU_ITEM', 'CREATE_RESOURCE_MENU', 'Resource for Menu Creation', '/webconsole/newResource.html');

INSERT INTO RES_TO_RES_MEMBERSHIP (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('RESOURCE_MENU_ROOT', 'CREATE_RESOURCE_MENU');

INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('CR_RES_DISP_NAME', 'CREATE_RESOURCE_MENU', 'MENU_DISPLAY_NAME', 'Create New Resource');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('CR_RES_MENU_PUB', 'CREATE_RESOURCE_MENU', 'MENU_IS_PUBLIC', 'true');