/* script to edit menu for user management*/
UPDATE RES SET URL='/webconsole/users.html' WHERE RESOURCE_ID='USER';
UPDATE RES SET URL='/webconsole/users.html' WHERE RESOURCE_ID='QUERYUSER';

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, DESCRIPTION) VALUES('USER_MENU_ROOT', 'MENU_ITEM', 'USER_MENU_ROOT', 'Root for User Context Menu');
INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, DESCRIPTION) VALUES('USER_EDIT_MENU_ROOT', 'MENU_ITEM', 'USER_EDIT_MENU_ROOT', 'Root for Edit User Context Menu');
INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, DESCRIPTION, URL) VALUES('NEW_USER', 'MENU_ITEM', 'NEW_USER', 'New User Context Menu','/webconsole/newUser.html');

UPDATE RES SET URL='/webconsole/newUser.html' WHERE RESOURCE_ID='ADDUSER';

UPDATE res_to_res_membership SET RESOURCE_ID='USER_MENU_ROOT' WHERE RESOURCE_ID='USER' and MEMBER_RESOURCE_ID='ADDUSER';
UPDATE res_to_res_membership SET RESOURCE_ID='USER_EDIT_MENU_ROOT' WHERE RESOURCE_ID='USER';
UPDATE res_to_res_membership SET RESOURCE_ID='USER_EDIT_MENU_ROOT' WHERE RESOURCE_ID='QUERYUSER';
INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('USER_EDIT_MENU_ROOT', 'NEW_USER');

INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('ADDUSER_MENU_PUB', 'ADDUSER', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('USER_MENU_PUB', 'USER', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('USER_BULK_MENU_PUB', 'USER_BULK', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('USERSUMMARY_MENU_PUB', 'USERSUMMARY', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('USERROLE_MENU_PUB', 'USERROLE', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('USERPSWDRESET_MENU_PUB', 'USERPSWDRESET', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('USERORG_MENU_PUB', 'USERORG', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('USERIDENTITY_MENU_PUB', 'USERIDENTITY', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('USERHISTORY_MENU_PUB', 'USERHISTORY', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('USERGROUP_MENU_PUB', 'USERGROUP', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('USERATTR_MENU_PUB', 'USERATTR', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('QUERYUSER_MENU_PUB', 'QUERYUSER', 'MENU_IS_PUBLIC', 'true');

INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('NEW_USER_MENU_PUB', 'NEW_USER', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('NEW_USER_MENU_DISPLAY', 'NEW_USER', 'MENU_DISPLAY_NAME', 'Add');