
use openiam;

DELETE FROM res_to_res_membership WHERE RESOURCE_ID IN(
	SELECT RESOURCE_ID FROM RES WHERE NAME IS NULL
);

DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID IN(
	SELECT RESOURCE_ID FROM RES WHERE NAME IS NULL
);

DELETE FROM RESOURCE_GROUP WHERE RESOURCE_ID IN(
	SELECT RESOURCE_ID FROM RES WHERE NAME IS NULL
);

DELETE FROM RESOURCE_PRIVILEGE WHERE RESOURCE_ID IN(
	SELECT RESOURCE_ID FROM RES WHERE NAME IS NULL
);

DELETE FROM RESOURCE_POLICY WHERE RESOURCE_ID IN(
	SELECT RESOURCE_ID FROM RES WHERE NAME IS NULL
);

DELETE FROM RESOURCE_PROP WHERE RESOURCE_ID IN(
	SELECT RESOURCE_ID FROM RES WHERE NAME IS NULL
);

DELETE FROM RESOURCE_ROLE WHERE RESOURCE_ID IN(
	SELECT RESOURCE_ID FROM RES WHERE NAME IS NULL
);

DELETE FROM RESOURCE_USER WHERE RESOURCE_ID IN(
	SELECT RESOURCE_ID FROM RES WHERE NAME IS NULL
);

DELETE FROM RES WHERE NAME IS NULL;

ALTER TABLE RES MODIFY COLUMN NAME VARCHAR(40) NOT NULL;

ALTER TABLE RES MODIFY COLUMN RESOURCE_TYPE_ID VARCHAR(20) NOT NULL;