use openiam;

DELETE FROM GRP_ATTRIBUTES WHERE GRP_ID IS NULL;
DELETE FROM GRP_ROLE WHERE GRP_ID IS NULL;
DELETE FROM grp_to_grp_membership WHERE GROUP_ID IS NULL OR MEMBER_GROUP_ID IS NULL;
DELETE FROM RESOURCE_GROUP WHERE GRP_ID IS NULL;
DELETE FROM USER_GRP WHERE GRP_ID IS NULL;
DELETE FROM GRP WHERE GRP_ID IS NULL;

ALTER TABLE GRP_ATTRIBUTES MODIFY COLUMN GRP_ID VARCHAR(32) NOT NULL;
ALTER TABLE GRP_ROLE MODIFY COLUMN GRP_ID VARCHAR(32) NOT NULL;
ALTER TABLE RESOURCE_GROUP MODIFY COLUMN GRP_ID VARCHAR(32) NOT NULL;
ALTER TABLE USER_GRP MODIFY COLUMN GRP_ID VARCHAR(32) NOT NULL;
ALTER TABLE GRP MODIFY COLUMN GRP_ID VARCHAR(32) NOT NULL;


DELETE FROM RESOURCE_GROUP;

ALTER TABLE RESOURCE_GROUP ADD CONSTRAINT UNIQUE_RESOURCE_GROUP UNIQUE (GRP_ID, RESOURCE_ID);