use openiam;

ALTER TABLE RES DROP COLUMN NODE_LEVEL;
ALTER TABLE RES DROP COLUMN SENSITIVE_APP;
ALTER TABLE RES DROP COLUMN RESOURCE_PARENT;


ALTER TABLE ROLE DROP COLUMN PROVISION_OBJ_NAME;
ALTER TABLE ROLE DROP COLUMN PARENT_ROLE_ID;
ALTER TABLE ROLE DROP COLUMN INHERIT_FROM_PARENT;
ALTER TABLE ROLE DROP COLUMN ROLE_APPROVER_ID;
ALTER TABLE ROLE DROP COLUMN ROLE_END_DATE;