use openiam;

DELIMITER $$

CREATE TRIGGER ON_USER_INSERT 
BEFORE 
INSERT ON USERS 
	FOR EACH ROW
	BEGIN
		SET NEW.CREATE_DATE = NOW();
		SET NEW.LAST_UPDATE = NOW();
	END$$
	
CREATE TRIGGER ON_USER_UPDATE
BEFORE 
UPDATE ON USERS 
	FOR EACH ROW
	BEGIN
		SET NEW.LAST_UPDATE = NOW();
	END$$
	
DELIMITER ;