use openiam;

ALTER TABLE EMAIL_ADDRESS 
	CHANGE COLUMN IS_DEFAULT IS_DEFAULT CHAR(1) NULL DEFAULT 'N', 
	CHANGE COLUMN ACTIVE ACTIVE CHAR(1) NULL DEFAULT 'Y';

ALTER TABLE ADDRESS
	CHANGE COLUMN IS_DEFAULT IS_DEFAULT CHAR(1) NULL DEFAULT 'N',
	CHANGE COLUMN ACTIVE ACTIVE CHAR(1) NULL DEFAULT 'Y';

ALTER TABLE PHONE
	CHANGE COLUMN IS_DEFAULT IS_DEFAULT CHAR(1) NULL DEFAULT 'N',
	CHANGE COLUMN ACTIVE ACTIVE CHAR(1) NULL DEFAULT 'Y';

update EMAIL_ADDRESS
	set IS_DEFAULT = case when IS_DEFAULT is null or IS_DEFAULT='0' THEN 'N' ELSE 'Y' END,
	    ACTIVE = case when ACTIVE is null or ACTIVE='0' THEN 'N' ELSE 'Y' END;

update ADDRESS
	set IS_DEFAULT = case when IS_DEFAULT is null or IS_DEFAULT='0' THEN 'N' ELSE 'Y' END,
	    ACTIVE = case when ACTIVE is null or ACTIVE='0' THEN 'N' ELSE 'Y' END;

update PHONE
	set IS_DEFAULT = case when IS_DEFAULT is null or IS_DEFAULT='0' THEN 'N' ELSE 'Y' END,
	    ACTIVE = case when ACTIVE is null or ACTIVE='0' THEN 'N' ELSE 'Y' END;
