use openiam;

ALTER TABLE EMAIL_ADDRESS ADD COLUMN LAST_UPDATE TIMESTAMP NULL;
ALTER TABLE EMAIL_ADDRESS ADD COLUMN CREATE_DATE TIMESTAMP NULL DEFAULT NOW();

DELIMITER $$

CREATE TRIGGER ON_EMAIL_INSERT 
BEFORE 
INSERT ON EMAIL_ADDRESS 
	FOR EACH ROW
	BEGIN
		SET NEW.CREATE_DATE = NOW();
		SET NEW.LAST_UPDATE = NOW();
	END$$
	
CREATE TRIGGER ON_EMAIL_UPDATE
BEFORE 
UPDATE ON EMAIL_ADDRESS 
	FOR EACH ROW
	BEGIN
		SET NEW.LAST_UPDATE = NOW();
	END$$
	
DELIMITER ;


ALTER TABLE PHONE ADD COLUMN LAST_UPDATE TIMESTAMP NULL;
ALTER TABLE PHONE ADD COLUMN CREATE_DATE TIMESTAMP NULL DEFAULT NOW();

DELIMITER $$

CREATE TRIGGER ON_PHONE_INSERT 
BEFORE 
INSERT ON PHONE 
	FOR EACH ROW
	BEGIN
		SET NEW.CREATE_DATE = NOW();
		SET NEW.LAST_UPDATE = NOW();
	END$$
	
CREATE TRIGGER ON_PHONE_UPDATE
BEFORE 
UPDATE ON PHONE 
	FOR EACH ROW
	BEGIN
		SET NEW.LAST_UPDATE = NOW();
	END$$
	
DELIMITER ;

ALTER TABLE ADDRESS ADD COLUMN LAST_UPDATE TIMESTAMP NULL;
ALTER TABLE ADDRESS ADD COLUMN CREATE_DATE TIMESTAMP NULL DEFAULT NOW();

DELIMITER $$

CREATE TRIGGER ON_ADDRESS_INSERT 
BEFORE 
INSERT ON ADDRESS 
	FOR EACH ROW
	BEGIN
		SET NEW.CREATE_DATE = NOW();
		SET NEW.LAST_UPDATE = NOW();
	END$$
	
CREATE TRIGGER ON_ADDRESS_UPDATE
BEFORE 
UPDATE ON ADDRESS 
	FOR EACH ROW
	BEGIN
		SET NEW.LAST_UPDATE = NOW();
	END$$
	
DELIMITER ;