use openiam;

ALTER TABLE METADATA_ELEMENT DROP COLUMN MIN_LEN;
ALTER TABLE METADATA_ELEMENT DROP COLUMN MAX_LEN;
ALTER TABLE METADATA_ELEMENT DROP COLUMN TEXT_CASE;
ALTER TABLE METADATA_ELEMENT DROP COLUMN MIN_VALUE;
ALTER TABLE METADATA_ELEMENT DROP COLUMN MAX_VALUE;
ALTER TABLE METADATA_ELEMENT DROP COLUMN DEFAULT_VALUE;
ALTER TABLE METADATA_ELEMENT DROP COLUMN VALUE_LIST;
ALTER TABLE METADATA_ELEMENT DROP COLUMN LABEL;
ALTER TABLE METADATA_ELEMENT DROP COLUMN MULTI_VALUE;
ALTER TABLE METADATA_ELEMENT DROP COLUMN UI_TYPE;
ALTER TABLE METADATA_ELEMENT DROP COLUMN UI_OBJECT_SIZE;
ALTER TABLE METADATA_ELEMENT DROP COLUMN VALUE_SRC;

ALTER TABLE METADATA_ELEMENT ADD TEMP_AUDITABLE CHAR(1) NULL DEFAULT 'Y';
UPDATE METADATA_ELEMENT SET TEMP_AUDITABLE='Y' WHERE AUDITABLE=1;
UPDATE METADATA_ELEMENT SET TEMP_AUDITABLE='N' WHERE AUDITABLE=0;
ALTER TABLE METADATA_ELEMENT DROP COLUMN AUDITABLE;
ALTER TABLE METADATA_ELEMENT CHANGE TEMP_AUDITABLE AUDITABLE CHAR(1) NOT NULL DEFAULT 'Y';

ALTER TABLE METADATA_ELEMENT ADD TEMP_REQUIRED CHAR(1) NULL DEFAULT 'N';
UPDATE METADATA_ELEMENT SET TEMP_REQUIRED='Y' WHERE REQUIRED=1;
UPDATE METADATA_ELEMENT SET TEMP_REQUIRED='N' WHERE REQUIRED=0;
ALTER TABLE METADATA_ELEMENT DROP COLUMN REQUIRED;
ALTER TABLE METADATA_ELEMENT CHANGE TEMP_REQUIRED REQUIRED CHAR(1) NOT NULL DEFAULT 'N';

ALTER TABLE METADATA_ELEMENT ADD TEMP_SELF_EDITABLE CHAR(1) NULL DEFAULT 'N';
UPDATE METADATA_ELEMENT SET TEMP_SELF_EDITABLE='Y' WHERE SELF_EDITABLE=1;
UPDATE METADATA_ELEMENT SET TEMP_SELF_EDITABLE='N' WHERE SELF_EDITABLE=0;
ALTER TABLE METADATA_ELEMENT DROP COLUMN SELF_EDITABLE;
ALTER TABLE METADATA_ELEMENT CHANGE TEMP_SELF_EDITABLE SELF_EDITABLE CHAR(1) NOT NULL DEFAULT 'N';

ALTER TABLE METADATA_ELEMENT DROP COLUMN SELF_VIEWABLE;