use openiam;

DELIMITER $$

DROP PROCEDURE IF EXISTS USER_SCHEMA_CHANGE$$

CREATE PROCEDURE USER_SCHEMA_CHANGE()
	BEGIN
		IF EXISTS (SELECT * FROM information_schema.TABLE_CONSTRAINTS WHERE TABLE_SCHEMA = 'openiam' AND TABLE_NAME='USERS' AND CONSTRAINT_NAME = 'FK_USERS_DEPARTMENT') THEN
			ALTER TABLE USERS DROP FOREIGN KEY FK_USERS_DEPARTMENT;
 		END IF;

        IF EXISTS (SELECT * FROM information_schema.TABLE_CONSTRAINTS WHERE TABLE_SCHEMA = 'openiam' AND TABLE_NAME='USERS' AND CONSTRAINT_NAME = 'FK_USERS_DIVISION') THEN
			ALTER TABLE USERS DROP FOREIGN KEY FK_USERS_DIVISION;
 		END IF;



	END$$
DELIMITER ;

call USER_SCHEMA_CHANGE();
DROP PROCEDURE USER_SCHEMA_CHANGE;


update USERS set DIVISION=null where DIVISION='';
update USERS set DEPT_CD=null where DEPT_CD='';


ALTER TABLE USERS
    DROP COLUMN DEL_ADMIN,
    ADD CONSTRAINT FK_USERS_DEPARTMENT FOREIGN KEY (DEPT_CD) REFERENCES COMPANY (COMPANY_ID),
    ADD CONSTRAINT FK_USERS_DIVISION FOREIGN KEY (DIVISION) REFERENCES COMPANY (COMPANY_ID);