use openiam;

DROP TABLE IF EXISTS AUTH_RESOURCE_ATTRIBUTE_MAP;
DROP TABLE IF EXISTS AUTH_RESOURCE_AM_ATTRIBUTE;

CREATE TABLE AUTH_RESOURCE_AM_ATTRIBUTE (
  AM_ATTRIBUTE_ID varchar(32) NOT NULL,
  ATTRIBUTE_NAME varchar(100) NOT NULL,
  PRIMARY KEY (AM_ATTRIBUTE_ID)
) ENGINE=InnoDB;


CREATE TABLE AUTH_RESOURCE_ATTRIBUTE_MAP (
  ATTRIBUTE_MAP_ID varchar(32) NOT NULL,
  PROVIDER_ID varchar(32) NOT NULL,
  TARGET_ATTRIBUTE_NAME varchar(100) NOT NULL,
  AM_ATTRIBUTE_ID varchar(100) NOT NULL,
  AM_POLICY_URL varchar(100) DEFAULT NULL,
  PRIMARY KEY (ATTRIBUTE_MAP_ID),
  UNIQUE KEY IDX_PROVIDER_ATTRIBUTE (PROVIDER_ID,TARGET_ATTRIBUTE_NAME),
  KEY FK_AUTH_AM_ATTR (AM_ATTRIBUTE_ID),
  KEY FK_PROVIDER_AUTH_RES_ATTR_MAP (PROVIDER_ID),
  CONSTRAINT FK_AUTH_AM_ATTR FOREIGN KEY (AM_ATTRIBUTE_ID) REFERENCES AUTH_RESOURCE_AM_ATTRIBUTE (AM_ATTRIBUTE_ID),
  CONSTRAINT FK_PROVIDER_AUTH_RES_ATTR_MAP FOREIGN KEY (PROVIDER_ID) REFERENCES AUTH_PROVIDER (PROVIDER_ID)
) ENGINE=InnoDB;