package org.openiam.idm.srvc.org.dto;

// Generated Jul 18, 2009 8:49:09 AM by Hibernate Tools 3.2.2.GA

import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.ParamDef;

import javax.persistence.*;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import java.util.Date;

/**
 * Object representing the User-Role relationship generated by hbm2java
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UserAffiliation", propOrder = {
        "userAffiliationId",
        "organizationId",
        "userId",
        "createDate",
        "startDate",
        "endDate",
        "status",
        "createdBy"
})
@Entity
@Table(name = "USER_AFFILIATION")
public class UserAffiliation implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = -3785768336629177182L;
    @Id
    @GeneratedValue(generator="system-uuid")
    @GenericGenerator(name="system-uuid", strategy = "uuid")
    @Column(name="USER_AFFILIATION_ID", length=32, nullable = false)
    private String userAffiliationId;

    @Column(name="USER_ID",length = 32, nullable = false)
    private String userId;

    @Column(name="COMPANY_ID",length = 32, nullable = false)
    private String organizationId;

    @Column(name="STATUS",length = 20)
    private String status;

    @Column(name="CREATE_DATE",length = 19)
    @Temporal(TemporalType.TIMESTAMP)
    private Date createDate;

    @Column(name="START_DATE",length = 19)
    @Temporal(TemporalType.TIMESTAMP)
    private Date startDate;

    @Column(name="END_DATE",length = 19)
    @Temporal(TemporalType.TIMESTAMP)
    private Date endDate;

    @Column(name="CREATED_BY",length = 20)
    private String createdBy;

    public UserAffiliation() {
    }

    public UserAffiliation(String userId, String organizationId) {
        this.userId = userId;
        this.organizationId = organizationId;
        status = "ACTIVE";
        long curTime = System.currentTimeMillis();
        createDate = new Date(curTime);
        startDate = new Date(curTime);
    }


    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public Date getStartDate() {
        return startDate;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    public Date getEndDate() {
        return endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    public String getUserAffiliationId() {
        return userAffiliationId;
    }

    public void setUserAffiliationId(String userAffiliationId) {
        this.userAffiliationId = userAffiliationId;
    }

    public String getOrganizationId() {
        return organizationId;
    }

    public void setOrganizationId(String organizationId) {
        this.organizationId = organizationId;
    }
}
