use openiam;

DROP TABLE IF EXISTS USER_KEY
CREATE TABLE USER_KEY (
	USER_KEY_ID varchar(32) NOT NULL,
	USER_ID varchar(32) NOT NULL,
	`NAME` varchar(40) NOT NULL,
	`KEY` varchar(80) NOT NULL,
	primary key(USER_KEY_ID),
    CONSTRAINT `FK_USER_KEY_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`USER_ID`)
)  Engine=InnoDB;
