use openiam;
SET foreign_key_checks = 0;

DROP TABLE IF EXISTS AUTH_PROVIDER_TYPE;
CREATE TABLE AUTH_PROVIDER_TYPE(
  PROVIDER_TYPE varchar(32) NOT NULL,
  DESCRIPTION varchar(40) DEFAULT NULL,
  ACTIVE char(1) DEFAULT 'Y',
  primary key(PROVIDER_TYPE)
)ENGINE=InnoDB;

DROP TABLE IF EXISTS AUTH_ATTRIBUTE;
CREATE TABLE AUTH_ATTRIBUTE(
  AUTH_ATTRIBUTE_ID varchar(32) NOT NULL,
  ATTRIBUTE_NAME varchar(100) NOT NULL,
  PROVIDER_TYPE varchar(32) NOT NULL,
  DESCRIPTION varchar(255) NULL,
  REQUIRED char(1) DEFAULT 'N',
  DATA_TYPE varchar(20) NOT NULL DEFAULT 'singleValue',
  primary key(AUTH_ATTRIBUTE_ID),
  unique key IDX_ATTRIBUTE_PT(ATTRIBUTE_NAME, PROVIDER_TYPE),
  KEY FK_PROVIDER_TYPE_ATTRIBUTE (PROVIDER_TYPE),
  CONSTRAINT FK_PROVIDER_TYPE_ATTRIBUTE FOREIGN KEY (PROVIDER_TYPE) REFERENCES AUTH_PROVIDER_TYPE (PROVIDER_TYPE)
)ENGINE=InnoDB;

DROP TABLE IF EXISTS AUTH_PROVIDER;
CREATE TABLE AUTH_PROVIDER(
  PROVIDER_ID varchar(32) NOT NULL,
  PROVIDER_TYPE varchar(32) NOT NULL,
  MANAGED_SYS_ID varchar(32) NOT NULL,
  RESOURCE_ID varchar(32) NOT NULL,
  NAME varchar(50) NOT NULL,
  DESCRIPTION varchar(255) NULL,
  SIGN_REQUEST char(1) NOT NULL DEFAULT 'N',
  PUBLIC_KEY text NULL,
  PRIVATE_KEY text NULL,
  primary key(PROVIDER_ID),
  KEY FK_PROVIDER_TYPE_PROVIDER (PROVIDER_TYPE),
  KEY FK_MNG_AUTH_PROVIDER (MANAGED_SYS_ID),
  KEY FK_RES_AUTH_PROVIDER (RESOURCE_ID),
  CONSTRAINT FK_PROVIDER_TYPE_PROVIDER FOREIGN KEY (PROVIDER_TYPE) REFERENCES AUTH_PROVIDER_TYPE (PROVIDER_TYPE),
  CONSTRAINT FK_MNG_AUTH_PROVIDER FOREIGN KEY (MANAGED_SYS_ID) REFERENCES MANAGED_SYS (MANAGED_SYS_ID),
  CONSTRAINT FK_RES_AUTH_PROVIDER FOREIGN KEY (RESOURCE_ID) REFERENCES RES (RESOURCE_ID)
)ENGINE=InnoDB;

DROP TABLE IF EXISTS AUTH_PROVIDER_ATTRIBUTE;
CREATE TABLE AUTH_PROVIDER_ATTRIBUTE(
  PROVIDER_ATTRIBUTE_ID varchar(32) NOT NULL,
  PROVIDER_ID varchar(32) NOT NULL,
  AUTH_ATTRIBUTE_ID varchar(32) NOT NULL,
  VALUE varchar(255) NOT NULL,
  DATA_TYPE varchar(20) NOT NULL DEFAULT 'singleValue',
  primary key(PROVIDER_ATTRIBUTE_ID),
  unique key IDX_PROVIDER_ATTRIBUTE(PROVIDER_ID, AUTH_ATTRIBUTE_ID),
  KEY FK_PROVIDER_PROVIDER_ATTRIBUTE (PROVIDER_ID),
  KEY FK_PROVIDER_ATTRIBUTE (AUTH_ATTRIBUTE_ID),
  CONSTRAINT FK_PROVIDER_PROVIDER_ATTRIBUTE FOREIGN KEY (PROVIDER_ID) REFERENCES AUTH_PROVIDER (PROVIDER_ID),
  CONSTRAINT FK_PROVIDER_ATTRIBUTE FOREIGN KEY (AUTH_ATTRIBUTE_ID) REFERENCES AUTH_ATTRIBUTE (AUTH_ATTRIBUTE_ID)
)ENGINE=InnoDB;

DROP TABLE IF EXISTS AUTH_RESOURCE_ATTRIBUTE;
CREATE TABLE AUTH_RESOURCE_ATTRIBUTE (
  ATTRIBUTE_MAP_ID varchar(32) NOT NULL,
  RESOURCE_ID varchar(32) NOT NULL,
  TARGET_ATTRIBUTE_NAME varchar(100) NOT NULL,
  AM_ATTRIBUTE_NAME varchar(100) DEFAULT NULL,
  AM_POLICY_URL varchar(100) DEFAULT NULL,
  PRIMARY KEY (ATTRIBUTE_MAP_ID),
  UNIQUE KEY IDX_RESOURCE_ATTRIBUTE (RESOURCE_ID,TARGET_ATTRIBUTE_NAME),
  KEY FK_RES_AUTH_RESOURCE_ATTRIBUTE (RESOURCE_ID),
  CONSTRAINT FK_RES_AUTH_RESOURCE_ATTRIBUTE FOREIGN KEY (RESOURCE_ID) REFERENCES RES (RESOURCE_ID)
) ENGINE=InnoDB;
SET foreign_key_checks = 1;