
package org.openiam.idm.srvc.audit.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AuditDataService", targetNamespace = "urn:idm.openiam.org/srvc/audit/service")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AuditDataService {


    /**
     * 
     * @param id
     * @return
     *     returns org.openiam.idm.srvc.audit.service.IdmAuditLog
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLogRecord", targetNamespace = "urn:idm.openiam.org/srvc/audit/service", className = "org.openiam.idm.srvc.audit.service.GetLogRecord")
    @ResponseWrapper(localName = "getLogRecordResponse", targetNamespace = "urn:idm.openiam.org/srvc/audit/service", className = "org.openiam.idm.srvc.audit.service.GetLogRecordResponse")
    public IdmAuditLog getLogRecord(@WebParam(name = "id", targetNamespace = "") String id);

    /**
     * 
     * @param searchBean
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "count", targetNamespace = "urn:idm.openiam.org/srvc/audit/service", className = "org.openiam.idm.srvc.audit.service.Count")
    @ResponseWrapper(localName = "countResponse", targetNamespace = "urn:idm.openiam.org/srvc/audit/service", className = "org.openiam.idm.srvc.audit.service.CountResponse")
    public int count(@WebParam(name = "searchBean", targetNamespace = "") AuditLogSearchBean searchBean);

    /**
     * 
     * @param from
     * @param searchBean
     * @param size
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getIds", targetNamespace = "urn:idm.openiam.org/srvc/audit/service", className = "org.openiam.idm.srvc.audit.service.GetIds")
    @ResponseWrapper(localName = "getIdsResponse", targetNamespace = "urn:idm.openiam.org/srvc/audit/service", className = "org.openiam.idm.srvc.audit.service.GetIdsResponse")
    public List<String> getIds(@WebParam(name = "searchBean", targetNamespace = "") AuditLogSearchBean searchBean, @WebParam(name = "from", targetNamespace = "") int from, @WebParam(name = "size", targetNamespace = "") int size);

    /**
     * 
     * @param arg0
     * @return
     *     returns org.openiam.idm.srvc.audit.service.Response
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addLog", targetNamespace = "urn:idm.openiam.org/srvc/audit/service", className = "org.openiam.idm.srvc.audit.service.AddLog")
    @ResponseWrapper(localName = "addLogResponse", targetNamespace = "urn:idm.openiam.org/srvc/audit/service", className = "org.openiam.idm.srvc.audit.service.AddLogResponse")
    public Response addLog(@WebParam(name = "arg0", targetNamespace = "") IdmAuditLog arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns org.openiam.idm.srvc.audit.service.Response
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addLogs", targetNamespace = "urn:idm.openiam.org/srvc/audit/service", className = "org.openiam.idm.srvc.audit.service.AddLogs")
    @ResponseWrapper(localName = "addLogsResponse", targetNamespace = "urn:idm.openiam.org/srvc/audit/service", className = "org.openiam.idm.srvc.audit.service.AddLogsResponse")
    public Response addLogs(@WebParam(name = "arg0", targetNamespace = "") List<IdmAuditLog> arg0);

    /**
     * 
     * @param from
     * @param searchBean
     * @param size
     * @return
     *     returns java.util.List<org.openiam.idm.srvc.audit.service.IdmAuditLog>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findBeans", targetNamespace = "urn:idm.openiam.org/srvc/audit/service", className = "org.openiam.idm.srvc.audit.service.FindBeans")
    @ResponseWrapper(localName = "findBeansResponse", targetNamespace = "urn:idm.openiam.org/srvc/audit/service", className = "org.openiam.idm.srvc.audit.service.FindBeansResponse")
    public List<IdmAuditLog> findBeans(@WebParam(name = "searchBean", targetNamespace = "") AuditLogSearchBean searchBean, @WebParam(name = "from", targetNamespace = "") int from, @WebParam(name = "size", targetNamespace = "") int size);

}
