
package org.openiam.idm.srvc.audit.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AuditService", targetNamespace = "urn:idm.openiam.org/srvc/audit/service", wsdlLocation = "http://lnx1.openiamdemo.com:9080/openiam-esb/idmsrvc/AuditService?wsdl")
public class AuditService
    extends Service
{

    private final static URL AUDITSERVICE_WSDL_LOCATION;
    private final static WebServiceException AUDITSERVICE_EXCEPTION;
    private final static QName AUDITSERVICE_QNAME = new QName("urn:idm.openiam.org/srvc/audit/service", "AuditService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://lnx1.openiamdemo.com:9080/openiam-esb/idmsrvc/AuditService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AUDITSERVICE_WSDL_LOCATION = url;
        AUDITSERVICE_EXCEPTION = e;
    }

    public AuditService() {
        super(__getWsdlLocation(), AUDITSERVICE_QNAME);
    }

    public AuditService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AUDITSERVICE_QNAME, features);
    }

    public AuditService(URL wsdlLocation) {
        super(wsdlLocation, AUDITSERVICE_QNAME);
    }

    public AuditService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AUDITSERVICE_QNAME, features);
    }

    public AuditService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AuditService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AuditDataService
     */
    @WebEndpoint(name = "AuditWebServicePort")
    public AuditDataService getAuditWebServicePort() {
        return super.getPort(new QName("urn:idm.openiam.org/srvc/audit/service", "AuditWebServicePort"), AuditDataService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AuditDataService
     */
    @WebEndpoint(name = "AuditWebServicePort")
    public AuditDataService getAuditWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:idm.openiam.org/srvc/audit/service", "AuditWebServicePort"), AuditDataService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AUDITSERVICE_EXCEPTION!= null) {
            throw AUDITSERVICE_EXCEPTION;
        }
        return AUDITSERVICE_WSDL_LOCATION;
    }

}
