
package org.openiam.idm.srvc.res.service;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2012-10-19T20:37:11.707+04:00
 * Generated source version: 2.5.1
 * 
 */
 
public class KeyManagementWS_KeyManagementWSPort_Server{

    protected KeyManagementWS_KeyManagementWSPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new KeyManagementWSImpl();
        String address = "http://localhost:9090/KeyManagementWSPort";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new KeyManagementWS_KeyManagementWSPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
