
package org.openiam.idm.srvc.res.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "KeyManagementWS", targetNamespace = "urn:idm.openiam.org/srvc/res/service", wsdlLocation = "http://localhost:8080/openiam-esb/idmsrvc/KeyManagementWS?wsdl")
public class KeyManagementWS_Service
    extends Service
{

    private final static URL WSDL_LOCATION;
    private final static WebServiceException KEYMANAGEMENTWS_EXCEPTION;
    private final static QName KEYMANAGEMENTWS_QNAME = new QName("urn:idm.openiam.org/srvc/res/service", "KeyManagementWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/openiam-esb/idmsrvc/KeyManagementWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSDL_LOCATION = url;
        KEYMANAGEMENTWS_EXCEPTION = e;
    }

    public KeyManagementWS_Service() {
        super(getWsdlLocation(), KEYMANAGEMENTWS_QNAME);
    }

    public KeyManagementWS_Service(WebServiceFeature... features) {
        super(getWsdlLocation(), KEYMANAGEMENTWS_QNAME, features);
    }

    public KeyManagementWS_Service(URL wsdlLocation) {
        super(wsdlLocation, KEYMANAGEMENTWS_QNAME);
    }

    public KeyManagementWS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, KEYMANAGEMENTWS_QNAME, features);
    }

    public KeyManagementWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public KeyManagementWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns KeyManagementWS
     */
    @WebEndpoint(name = "KeyManagementWSPort")
    public KeyManagementWS getKeyManagementWSPort() {
        return super.getPort(new QName("urn:idm.openiam.org/srvc/res/service", "KeyManagementWSPort"), KeyManagementWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns KeyManagementWS
     */
    @WebEndpoint(name = "KeyManagementWSPort")
    public KeyManagementWS getKeyManagementWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:idm.openiam.org/srvc/res/service", "KeyManagementWSPort"), KeyManagementWS.class, features);
    }

    public static URL getWsdlLocation() {
        if (KEYMANAGEMENTWS_EXCEPTION!= null) {
            throw KEYMANAGEMENTWS_EXCEPTION;
        }
        return WSDL_LOCATION;
    }

}
