package org.openiam.idm.srvc.res.service;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2012-10-19T20:37:11.701+04:00
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "urn:idm.openiam.org/srvc/res/service", name = "KeyManagementWS")
@XmlSeeAlso({ObjectFactory.class})
public interface KeyManagementWS {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "refreshUserKeys", targetNamespace = "urn:idm.openiam.org/srvc/res/service", className = "org.openiam.idm.srvc.res.service.RefreshUserKeys")
    @WebMethod
    @ResponseWrapper(localName = "refreshUserKeysResponse", targetNamespace = "urn:idm.openiam.org/srvc/res/service", className = "org.openiam.idm.srvc.res.service.RefreshUserKeysResponse")
    public org.openiam.idm.srvc.res.service.Response refreshUserKeys();
}
