package org.openiam.idm.srvc.res.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2012-10-19T20:37:11.711+04:00
 * Generated source version: 2.5.1
 * 
 */
@WebServiceClient(name = "KeyManagementWS", 
                  wsdlLocation = "http://localhost:8080/openiam-esb/idmsrvc/KeyManagementWS?wsdl",
                  targetNamespace = "urn:idm.openiam.org/srvc/res/service") 
public class KeyManagementWS_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:idm.openiam.org/srvc/res/service", "KeyManagementWS");
    public final static QName KeyManagementWSPort = new QName("urn:idm.openiam.org/srvc/res/service", "KeyManagementWSPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/openiam-esb/idmsrvc/KeyManagementWS?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(KeyManagementWS_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/openiam-esb/idmsrvc/KeyManagementWS?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public KeyManagementWS_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public KeyManagementWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public KeyManagementWS_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public KeyManagementWS_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public KeyManagementWS_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public KeyManagementWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns KeyManagementWS
     */
    @WebEndpoint(name = "KeyManagementWSPort")
    public KeyManagementWS getKeyManagementWSPort() {
        return super.getPort(KeyManagementWSPort, KeyManagementWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns KeyManagementWS
     */
    @WebEndpoint(name = "KeyManagementWSPort")
    public KeyManagementWS getKeyManagementWSPort(WebServiceFeature... features) {
        return super.getPort(KeyManagementWSPort, KeyManagementWS.class, features);
    }

}
