
package org.openiam.idm.srvc.res.service;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "KeyManagementWS", targetNamespace = "urn:idm.openiam.org/srvc/res/service")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface KeyManagementWS {


    /**
     * 
     * @return
     *     returns org.openiam.idm.srvc.res.service.Response
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "generateMasterKey", targetNamespace = "urn:idm.openiam.org/srvc/res/service", className = "org.openiam.idm.srvc.res.service.GenerateMasterKey")
    @ResponseWrapper(localName = "generateMasterKeyResponse", targetNamespace = "urn:idm.openiam.org/srvc/res/service", className = "org.openiam.idm.srvc.res.service.GenerateMasterKeyResponse")
    public Response generateMasterKey();

}
