
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.openiam.idm.srvc.res.service;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2012-10-19T20:37:11.691+04:00
 * Generated source version: 2.5.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "KeyManagementWS",
                      portName = "KeyManagementWSPort",
                      targetNamespace = "urn:idm.openiam.org/srvc/res/service",
                      wsdlLocation = "file:/home/alexander/Development/openiam/iam-services/openiam-km/openiam-km-util/src/main/resources/KeyManagementWS.wsdl",
                      endpointInterface = "org.openiam.idm.srvc.res.service.KeyManagementWS")
                      
public class KeyManagementWSImpl implements KeyManagementWS {

    private static final Logger LOG = Logger.getLogger(KeyManagementWSImpl.class.getName());

    /* (non-Javadoc)
     * @see org.openiam.idm.srvc.res.service.KeyManagementWS#refreshUserKeys(*
     */
    public org.openiam.idm.srvc.res.service.Response refreshUserKeys() { 
        LOG.info("Executing operation refreshUserKeys");
        try {
            org.openiam.idm.srvc.res.service.Response _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
