use openiam;

DELETE FROM URI_PATTERN_META_VALUE WHERE AM_ATTRIBUTE_ID='User.email';
UPDATE AUTH_RESOURCE_ATTRIBUTE_MAP SET AM_ATTRIBUTE_ID=NULL, AM_POLICY_URL='AM/PrimaryEmail.groovy' WHERE AM_ATTRIBUTE_ID='User.email';
DELETE FROM AUTH_RESOURCE_AM_ATTRIBUTE WHERE AM_ATTRIBUTE_ID='User.email';