use openiam;

DELETE FROM RESOURCE_USER WHERE RESOURCE_ID IN('CONTENT_PROV_SERVER', 'CONTENT_PROV_URL_PATTERN', 'URI_PATTERN_EDT_PTRN_SEARCH', 'URI_PATTERN_EDIT_META', 'URI_META_EDIT', 'URI_META_BACK', 'BACK_TO_CP');
DELETE FROM RESOURCE_ROLE WHERE RESOURCE_ID IN('CONTENT_PROV_SERVER', 'CONTENT_PROV_URL_PATTERN', 'URI_PATTERN_EDT_PTRN_SEARCH', 'URI_PATTERN_EDIT_META', 'URI_META_EDIT', 'URI_META_BACK', 'BACK_TO_CP');
DELETE FROM RESOURCE_PROP WHERE RESOURCE_ID IN('CONTENT_PROV_SERVER', 'CONTENT_PROV_URL_PATTERN', 'URI_PATTERN_EDT_PTRN_SEARCH', 'URI_PATTERN_EDIT_META', 'URI_META_EDIT', 'URI_META_BACK', 'BACK_TO_CP');
DELETE FROM RESOURCE_GROUP WHERE RESOURCE_ID IN('CONTENT_PROV_SERVER', 'CONTENT_PROV_URL_PATTERN', 'URI_PATTERN_EDT_PTRN_SEARCH', 'URI_PATTERN_EDIT_META', 'URI_META_EDIT', 'URI_META_BACK', 'BACK_TO_CP');
DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID IN('CONTENT_PROV_SERVER', 'CONTENT_PROV_URL_PATTERN', 'URI_PATTERN_EDT_PTRN_SEARCH', 'URI_PATTERN_EDIT_META', 'URI_META_EDIT', 'URI_META_BACK', 'BACK_TO_CP');
DELETE FROM res_to_res_membership WHERE RESOURCE_ID IN('CONTENT_PROV_SERVER', 'CONTENT_PROV_URL_PATTERN', 'URI_PATTERN_EDT_PTRN_SEARCH', 'URI_PATTERN_EDIT_META', 'URI_META_EDIT', 'URI_META_BACK', 'BACK_TO_CP');
DELETE FROM RES WHERE RESOURCE_ID IN('CONTENT_PROV_SERVER', 'CONTENT_PROV_URL_PATTERN', 'URI_PATTERN_EDT_PTRN_SEARCH', 'URI_PATTERN_EDIT_META', 'URI_META_EDIT', 'URI_META_BACK', 'BACK_TO_CP');


UPDATE RESOURCE_PROP SET NAME='MENU_DISPLAY_NAME', PROP_VALUE='Content Provider Search' WHERE RESOURCE_PROP_ID='URI_PATTERN_EDT_PROV_SEARCH_DESC';



INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, DESCRIPTION) VALUES('URI_META_EDIT', 'MENU_ITEM', 'URI_META_EDIT', 'URI Meta Root');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('URI_META_EDIT_PUB', 'URI_META_EDIT', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('URI_META_EDIT_DESC', 'URI_META_EDIT', 'MENU_DISPLAY_NAME', 'URI Meta Root Item');


INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, DESCRIPTION, URL) VALUES('URI_META_BACK', 'MENU_ITEM', 'URI_META_BACK', 'Back To Pattern', '/webconsole-am/editProviderPattern.html');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('URI_META_BACK_PUB', 'URI_META_BACK', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('URI_META_BACK_DESC', 'URI_META_BACK', 'MENU_DISPLAY_NAME', 'Back To Pattern');

INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('URI_META_EDIT', 'URI_META_BACK');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, DESCRIPTION, URL) VALUES('BACK_TO_CP', 'MENU_ITEM', 'BACK_TO_CP', 'Back To Content Provider', '/webconsole-am/editContentProvider.html');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('BACK_TO_CP_PUB', 'BACK_TO_CP', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('BACK_TO_CP_DESC', 'BACK_TO_CP', 'MENU_DISPLAY_NAME', 'Back To Content Provider');

INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('URI_PATTERN_EDIT', 'BACK_TO_CP');