use openiam;

DROP TABLE IF EXISTS USER_KEY;
CREATE TABLE USER_KEY (
	USER_KEY_ID varchar(32) NOT NULL,
	USER_ID varchar(32) NOT NULL,
	NAME varchar(40) NOT NULL,
	KEY_VALUE varchar(255) NOT NULL,
	primary key(USER_KEY_ID),
    CONSTRAINT FK_USER_KEY_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID)
)  Engine=InnoDB;

ALTER TABLE USERS ADD COLUMN SYSTEM_FLAG VARCHAR(1) NULL;
ALTER TABLE LOGIN CHANGE COLUMN PASSWORD PASSWORD VARCHAR(255) NULL DEFAULT NULL,
                    CHANGE COLUMN PWD_EQUIVALENT_TOKEN PWD_EQUIVALENT_TOKEN VARCHAR(255) NULL DEFAULT NULL;

ALTER TABLE MANAGED_SYS CHANGE COLUMN PSWD PSWD VARCHAR(255) NULL DEFAULT NULL;
ALTER TABLE PWD_HISTORY CHANGE COLUMN PASSWORD PASSWORD VARCHAR(255) NULL DEFAULT NULL;

