use openiam;

ALTER TABLE AUTH_RESOURCE_ATTRIBUTE_MAP DROP FOREIGN KEY FK_AUTH_AM_ATTR;
ALTER TABLE AUTH_RESOURCE_ATTRIBUTE_MAP
  ADD COLUMN ATTRIBUTE_VALUE VARCHAR(100) NULL DEFAULT NULL,
  ADD COLUMN ATTRIBUTE_TYPE VARCHAR(32) NOT NULL,
  CHANGE COLUMN AM_ATTRIBUTE_ID AM_ATTRIBUTE_ID VARCHAR(100) NULL DEFAULT NULL,
  ADD CONSTRAINT FK_AUTH_AM_ATTR FOREIGN KEY (AM_ATTRIBUTE_ID) REFERENCES AUTH_RESOURCE_AM_ATTRIBUTE (AM_ATTRIBUTE_ID);
