use openiam;

DELETE FROM EMAIL_ADDRESS WHERE PARENT_ID NOT IN (SELECT USER_ID FROM USERS);
DELETE FROM PHONE WHERE PARENT_ID NOT IN (SELECT USER_ID FROM USERS);
DELETE FROM ADDRESS WHERE PARENT_ID NOT IN (SELECT USER_ID FROM USERS);

ALTER TABLE EMAIL_ADDRESS ADD CONSTRAINT EMAIL_ADDRESS_USER_FK FOREIGN KEY (PARENT_ID) REFERENCES USERS(USER_ID);
ALTER TABLE PHONE ADD CONSTRAINT PHONE_USER_FK FOREIGN KEY (PARENT_ID) REFERENCES USERS(USER_ID);
ALTER TABLE ADDRESS ADD CONSTRAINT ADDRESS_USER_FK FOREIGN KEY (PARENT_ID) REFERENCES USERS(USER_ID);