use openiam;
ALTER TABLE CATEGORY_LANGUAGE DROP FOREIGN KEY FK_CATEGORY_LANGUAGE_LANGUAGE;
ALTER TABLE CATEGORY_LANGUAGE CHANGE COLUMN LANGUAGE_CD LANGUAGE_ID VARCHAR(32) NOT NULL;
ALTER TABLE EXCLUDE_WORD_LIST DROP FOREIGN KEY FK_EXCLUDE_WORD_LIST_LANGUAGE;
ALTER TABLE EXCLUDE_WORD_LIST CHANGE COLUMN LANGUAGE_CD LANGUAGE_ID VARCHAR(32) NOT NULL;


truncate table LANGUAGE;
ALTER TABLE LANGUAGE
    DROP PRIMARY KEY,
    DROP COLUMN LANGUAGE_CD,
    ADD COLUMN ID VARCHAR(32) NOT NULL FIRST,
    ADD COLUMN IS_USED VARCHAR(1) NOT NULL DEFAULT 'N',
    CHANGE COLUMN LOCALE LOCALE VARCHAR(10) NULL DEFAULT NULL,
    ADD PRIMARY KEY(ID);


ALTER TABLE EXCLUDE_WORD_LIST
  ADD CONSTRAINT FK_EXCLUDE_WORD_LIST_LANGUAGE FOREIGN KEY (LANGUAGE_ID) REFERENCES LANGUAGE(ID);
ALTER TABLE CATEGORY_LANGUAGE
  ADD CONSTRAINT FK_CATEGORY_LANGUAGE_LANGUAGE FOREIGN KEY (LANGUAGE_ID) REFERENCES LANGUAGE(ID);