use openiam;

ALTER TABLE EMAIL_ADDRESS MODIFY NAME VARCHAR(100) NULL;

ALTER TABLE ADDRESS MODIFY NAME VARCHAR(100) NULL;
ALTER TABLE ADDRESS MODIFY COUNTRY VARCHAR(100) NULL;
ALTER TABLE ADDRESS MODIFY CITY VARCHAR(100) NULL;
ALTER TABLE ADDRESS MODIFY STATE VARCHAR(100) NULL;
ALTER TABLE ADDRESS MODIFY POSTAL_CD VARCHAR(100) NULL;
ALTER TABLE ADDRESS MODIFY BLDG_NUM VARCHAR(100) NULL;