use openiam;

DROP TABLE IF EXISTS METADATA_ELEMENT_TEMPLATE_URI_PATTERN_XREF;

CREATE TABLE METADATA_ELEMENT_TEMPLATE_URI_PATTERN_XREF (
	TEMPLATE_ID VARCHAR(32) NOT NULL,
	URI_PATTERN_ID VARCHAR(32) NOT NULL,
	CONSTRAINT TEMPLATE_PATTERN_XREF_TEMPLATE_FK FOREIGN KEY (TEMPLATE_ID) REFERENCES METADATA_ELEMENT_PAGE_TEMPLATE(ID),
	CONSTRAINT TEMPLATE_PATTERN_XREF_PATTERN_FK FOREIGN KEY (URI_PATTERN_ID) REFERENCES URI_PATTERN(URI_PATTERN_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;