use openiam;

ALTER TABLE URI_PATTERN_META DROP FOREIGN KEY URI_PATTERN_META_URI_PATTERN_META_TYPE_FK;
ALTER TABLE URI_PATTERN_META DROP FOREIGN KEY URI_PATTERN_META_URI_PATTERN_FK;
ALTER TABLE URI_PATTERN_META
    ADD COLUMN URI_PATTERN_NAME VARCHAR(100) NOT NULL,
    DROP INDEX URI_PATTERN_META_UNIQUE;

ALTER TABLE URI_PATTERN_META
  ADD CONSTRAINT URI_PATTERN_META_URI_PATTERN_FK
    FOREIGN KEY (URI_PATTERN_ID ) REFERENCES URI_PATTERN (URI_PATTERN_ID),
  ADD CONSTRAINT URI_PATTERN_META_URI_PATTERN_META_TYPE_FK
    FOREIGN KEY (URI_PATTERN_META_TYPE_ID) REFERENCES URI_PATTERN_META_TYPE (URI_PATTERN_META_TYPE_ID),
  ADD INDEX URI_PATTERN_META_URI_PATTERN_FK (URI_PATTERN_ID ASC),
  ADD INDEX URI_PATTERN_META_URI_PATTERN_META_TYPE_FK (URI_PATTERN_META_TYPE_ID ASC);