use openiam;

ALTER TABLE CONTENT_PROVIDER DROP INDEX UNIQUE_CP_PATTERN;
ALTER TABLE CONTENT_PROVIDER DROP COLUMN CONTEXT_PATH;
ALTER TABLE CONTENT_PROVIDER ADD CONSTRAINT UNIQUE_CP_PATTERN UNIQUE(DOMAIN_PATTERN, iS_SSL);