package org.openiam.idm.srvc.audit.constant;

/**
 * Created with IntelliJ IDEA.
 * User: alexander
 * Date: 10/2/13
 * Time: 3:23 AM
 * To change this template use File | Settings | File Templates.
 */
public enum AuditAction {
    AUTHENTICATION("AUTHENTICATION"),
    LOGOUT("LOGOUT"),
	LOGIN("LOGIN"),
	SAML_LOGIN("SAML_LOGIN"),
    SAVE_GROUP("SAVE GROUP"),
    ADD_GROUP("CREATE GROUP"),
    GET_GROUP("GET GROUP"),
    DELETE_GROUP("DELETE GROUP"),
    GET_CHILD_GROUP_NUM("GET NUMBER OF CHILD GROUPS"),
    PASSWORD_POLICY_CHANGE("PASSWORD_POLICY_CHANGE"),
    CHANGE_PASSWORD("CHANGE_PASSWORD"),
    SAVE_IT_POLICY("SAVE_IT_POLICY"),
    RESET_IT_POLICY("RESET_IT_POLICY"),
    DELETE_POLICY_MAP("DELETE_POLICY_MAP"),
    SAVE_POLICY_MAP("SAVE_POLICY_MAP"),
    GET_CHILD_GROUP("GET CHILD GROUPS"),
    GET_PARENT_GROUP_NUM("GET NUMBER OF PARENT GROUPS"),
    GET_PARENT_GROUP("GET PARENT GROUPS"),
    IS_USER_GROUP("CHECK IF USER IS IN GROUP"),
    ADD_USER_TO_GROUP("ADD USER TO GROUP"),
    REMOVE_USER_FROM_GROUP("REMOVE USER FROM GROUP"),
    ADD_ATTRIBUTE_TO_GROUP("ADD ATTRIBUTE TO GROUP"),
    REMOVE_GROUP_ATTRIBUTE("REMOVE GROUP ATTRIBUTE"),
    ADD_CHILD_GROUP("ADD CHILD GROUP"),
    REMOVE_CHILD_GROUP("REMOVE CHILD GROUP"),
    CAN_ADD_USER_TO_GROUP("CHECK IF USER CAN BE ADDED TO GROUP"),
    CAN_REMOVE_USER_FROM_GROUP("CHECK IF USER CAN BE REMOVED FROM GROUP"),
    SEARCH_GROUP("SEARCH GROUP"),
    GET_GROUP_NUM("GET NUMBER OF GROUP"),
    GET_GROUP_NUM_FOR_USER("GET NUMBER OF GROUP FOR USER"),
    GET_GROUP_NUM_FOR_RESOURCE("GET NUMBER OF GROUP FOR RESOURCE"),
    GET_GROUP_NUM_FOR_ROLE("GET NUMBER OF GROUP FOR ROLE"),
    GET_GROUP_FOR_USER("GET GROUPS FOR USER"),
    GET_GROUP_FOR_RESOURCE("GET GROUPS FOR RESOURCE"),
    GET_GROUP_FOR_ROLE("GET GROUPS FOR ROLE");

    private String value;

    private AuditAction(String val){
        this.value=val;
    }
    public String value(){
        return this.value;
    }
}
