use openiam;

INSERT INTO AUTH_RESOURCE_AM_ATTRIBUTE (AM_ATTRIBUTE_ID, ATTRIBUTE_NAME) VALUES('Login.login', 'Principal');
INSERT INTO AUTH_RESOURCE_AM_ATTRIBUTE (AM_ATTRIBUTE_ID, ATTRIBUTE_NAME) VALUES('User.email', 'Email Address');
INSERT INTO AUTH_RESOURCE_AM_ATTRIBUTE (AM_ATTRIBUTE_ID, ATTRIBUTE_NAME) VALUES('User.title', 'Functional Title');